# Importing libraries and Dataset

In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('Movies Recommendation.csv')

In [4]:
df.head()

Movie_ID      Movie_Title                       Movie_Genre Movie_Language  \
0         1       Four Rooms                      Crime Comedy             en   
1         2        Star Wars  Adventure Action Science Fiction             en   
2         3     Finding Nemo                  Animation Family             en   
3         4     Forrest Gump              Comedy Drama Romance             en   
4         5  American Beauty                             Drama             en   

   Movie_Budget  Movie_Popularity Movie_Release_Date  Movie_Revenue  \
0       4000000         22.876230         09-12-1995        4300000   
1      11000000        126.393695         25-05-1977      775398007   
2      94000000         85.688789         30-05-2003      940335536   
3      55000000        138.133331         06-07-1994      677945399   
4      15000000         80.878605         15-09-1999      356296601   

   Movie_Runtime  Movie_Vote  ...  \
0           98.0         6.5  ...   
1          121.0         8.1  ...   
2          100.0         7.6  ...   
3          142.0         8.2  ...   
4          122.0         7.9  ...   

                                      Movie_Homepage  \
0                                                NaN   
1  http://www.starwars.com/films/star-wars-episod...   
2              http://movies.disney.com/finding-nemo   
3                                                NaN   
4                      http://www.dreamworks.com/ab/   

                                      Movie_Keywords  \
0          hotel new year's eve witch bet hotel room   
1        android galaxy hermit death star lightsaber   
2  father son relationship harbor underwater fish...   
3  vietnam veteran hippie mentally disabled runni...   
4  male nudity female nudity adultery midlife cri...   

                                      Movie_Overview  \
0  It's Ted the Bellhop's first night on the job....   
1  Princess Leia is captured and held hostage by ...   
2  Nemo, an adventurous young clownfish, is unexp...   
3  A man with a low IQ has accomplished great thi...   
4  Lester Burnham, a depressed suburban father in...   

                              Movie_Production_House  \
0  [{"name": "Miramax Films", "id": 14}, {"name":...   
1  [{"name": "Lucasfilm", "id": 1}, {"name": "Twe...   
2     [{"name": "Pixar Animation Studios", "id": 3}]   
3          [{"name": "Paramount Pictures", "id": 4}]   
4  [{"name": "DreamWorks SKG", "id": 27}, {"name"...   

                            Movie_Production_Country  \
0  [{"iso_3166_1": "US", "name": "United States o...   
1  [{"iso_3166_1": "US", "name": "United States o...   
2  [{"iso_3166_1": "US", "name": "United States o...   
3  [{"iso_3166_1": "US", "name": "United States o...   
4  [{"iso_3166_1": "US", "name": "United States o...   

                      Movie_Spoken_Language  \
0  [{"iso_639_1": "en", "name": "English"}]   
1  [{"iso_639_1": "en", "name": "English"}]   
2  [{"iso_639_1": "en", "name": "English"}]   
3  [{"iso_639_1": "en", "name": "English"}]   
4  [{"iso_639_1": "en", "name": "English"}]   

                                       Movie_Tagline  \
0  Twelve outrageous guests. Four scandalous requ...   
1       A long time ago in a galaxy far, far away...   
2  There are 3.7 trillion fish in the ocean, they...   
3  The world will never be the same, once you've ...   
4                                       Look closer.   

                                          Movie_Cast  \
0  Tim Roth Antonio Banderas Jennifer Beals Madon...   
1  Mark Hamill Harrison Ford Carrie Fisher Peter ...   
2  Albert Brooks Ellen DeGeneres Alexander Gould ...   
3  Tom Hanks Robin Wright Gary Sinise Mykelti Wil...   
4  Kevin Spacey Annette Bening Thora Birch Wes Be...   

                                          Movie_Crew   Movie_Director  
0  [{'name': 'Allison Anders', 'gender': 1, 'depa...   Allison Anders  
1  [{'name': 'George Lucas', 'gender': 2, 'depart...     George Lucas  
2  [{'na

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4760 entries, 0 to 4759
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Movie_ID                  4760 non-null   int64  
 1   Movie_Title               4760 non-null   object 
 2   Movie_Genre               4760 non-null   object 
 3   Movie_Language            4760 non-null   object 
 4   Movie_Budget              4760 non-null   int64  
 5   Movie_Popularity          4760 non-null   float64
 6   Movie_Release_Date        4760 non-null   object 
 7   Movie_Revenue             4760 non-null   int64  
 8   Movie_Runtime             4758 non-null   float64
 9   Movie_Vote                4760 non-null   float64
 10  Movie_Vote_Count          4760 non-null   int64  
 11  Movie_Homepage            1699 non-null   object 
 12  Movie_Keywords            4373 non-null   object 
 13  Movie_Overview            4757 non-null   object 
 14  Movie_Pr

In [10]:
df.dropna()

Movie_ID                                        Movie_Title  \
1            2                                          Star Wars   
2            3                                       Finding Nemo   
4            5                                    American Beauty   
9           10  Pirates of the Caribbean: The Curse of the Bla...   
10          11                                  Kill Bill: Vol. 1   
...        ...                                                ...   
4728      4755                                     Time to Choose   
4737      4765                                           Bad Moms   
4743      4772                                       Fight Valley   
4745      4774                                              Kicks   
4748      4777                                      The Dog Lover   

                           Movie_Genre Movie_Language  Movie_Budget  \
1     Adventure Action Science Fiction             en      11000000   
2                     Animation Family             en      94000000   
4                                Drama             en      15000000   
9             Adventure Fantasy Action             en     140000000   
10                        Action Crime             en      30000000   
...                                ...            ...           ...   
4728                       Documentary             en       3500000   
4737                            Comedy             en      20000000   
4743                      Action Drama             en      27000000   
4745                         Adventure             en             0   
4748                             Drama             en       2000000   

      Movie_Popularity Movie_Release_Date  Movie_Revenue  Movie_Runtime  \
1           126.393695         25-05-1977      775398007          121.0   
2            85.688789         30-05-2003      940335536          100.0   
4            80.878605         15-09-1999      356296601          122.0   
9           271.972889         09-07-2003      655011224          143.0   
10           79.754966         10-10-2003      180949000          111.0   
...                ...                ...            ...            ...   
4728          1.618138         04-09-2015              0          100.0   
4737         42.512296         28-07-2016      183936074          100.0   
4743          1.224105         22-07-2016              0           90.0   
4745          3.467923         09-09-2016              0           80.0   
4748          1.193219         08-07-2016              0          101.0   

      Movie_Vote  ...                                     Movie_Homepage  \
1            8.1  ...  http://www.starwars.com/films/star-wars-episod...   
2            7.6  ...              http://movies.disney.com/finding-nemo   
4            7.9  ...                      http://www.dreamworks.com/ab/   
9            7.5  ...  http://disney.go.com/disneyvideos/liveaction/p...   
10           7.7  ...   http://www.miramax.com/movie/kill-bill-volume-1/   
...          ...  ...                                                ...   
4728         0.0  ...                        http://www.timetochoose.com   
4737         6.3  ...                      http://stxmovies.com/badmoms/   
4743         3.9  ...                        http://www.fightvalley.com/   
4745         7.5  ...                 http://www.focusfeatures.com/kicks   
4748         5.3  ...                   http://www.thedoglovermovie.com/   

                                         Movie_Keywords  \
1           android galaxy hermit death star lightsaber   
2     father son relationship harbor underwater fish...   
4     male nudity female nudity adultery midlife cri...   
9     exotic island blacksmith east india trading co...   
10           japan coma martial arts kung fu underworld   
...                                                 ...   
4728                         climate change documentary   
4737                   alcohol bar par

# Feature_Selection

In [19]:
df_features = df[['Movie_Genre','Movie_Spoken_Language','Movie_Keywords','Movie_Production_Country','Movie_Cast']]

In [20]:
df_features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4760 entries, 0 to 4759
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Movie_Genre               4760 non-null   object
 1   Movie_Spoken_Language     4760 non-null   object
 2   Movie_Keywords            4373 non-null   object
 3   Movie_Production_Country  4760 non-null   object
 4   Movie_Cast                4733 non-null   object
dtypes: object(5)
memory usage: 186.1+ KB


In [21]:
df_features = df_features.dropna()

In [22]:
X = df_features['Movie_Genre']+' '+df_features['Movie_Spoken_Language']+' '+df_features['Movie_Keywords']+' '+df_features['Movie_Production_Country']+' '+df_features['Movie_Cast']

In [23]:
X

0       Crime Comedy [{"iso_639_1": "en", "name": "Eng...
1       Adventure Action Science Fiction [{"iso_639_1"...
2       Animation Family [{"iso_639_1": "en", "name": ...
3       Comedy Drama Romance [{"iso_639_1": "en", "nam...
4       Drama [{"iso_639_1": "en", "name": "English"}]...
                              ...                        
4751    Horror [{"iso_639_1": "en", "name": "English"}...
4752    History Drama War Action [{"iso_639_1": "en", ...
4754    Action Adventure Animation Family Fantasy [{"i...
4757    Thriller Drama [{"iso_639_1": "en", "name": "E...
4759    Documentary [] music actors legendary perfomer...
Length: 4364, dtype: object

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [25]:
tfidf = TfidfVectorizer()

In [26]:
X = tfidf.fit_transform(X)

In [27]:
X

<4364x12947 sparse matrix of type '<class 'numpy.float64'>'
	with 135313 stored elements in Compressed Sparse Row format>

# Getting Similarity Score using Cosine Similarity

In [28]:
from sklearn.metrics.pairwise import cosine_similarity

In [29]:
Similarity_Score = cosine_similarity(X)

In [32]:
print(Similarity_Score)
Similarity_Score.shape

[[1.         0.01969064 0.01783883 ... 0.1286528  0.02294662 0.00632509]
 [0.01969064 1.         0.01752695 ... 0.05266349 0.02254544 0.00621451]
 [0.01783883 0.01752695 1.         ... 0.05338339 0.02042515 0.00563006]
 ...
 [0.1286528  0.05266349 0.05338339 ... 1.         0.0284045  0.00804361]
 [0.02294662 0.02254544 0.02042515 ... 0.0284045  1.         0.00724212]
 [0.00632509 0.00621451 0.00563006 ... 0.00804361 0.00724212 1.        ]]


(4364, 4364)

# Getting Movie name as Input

In [45]:
Fav_Movie_Name = input('Enter your favourite movie name:')

Enter your favourite movie name:superman


In [46]:
All_Movies_Title = df['Movie_Title'].tolist()

In [47]:
import difflib as dl

In [48]:
Movie_Recommendation =  dl.get_close_matches(Fav_Movie_Name,All_Movies_Title)

In [52]:
print(Movie_Recommendation)
Close_Match = Movie_Recommendation[0]

['Superman', 'Superman II', 'Superman III']


In [55]:
Index_of_Close_Match_Movie = df[df.Movie_Title == Close_Match]['Movie_ID'].values[0]
print(Index_of_Close_Match_Movie)
Recommendation_Score = list(enumerate(Similarity_Score[Index_of_Close_Match_Movie]))
print(Recommendation_Score)
len(Recommendation_Score)

614
[(0, 0.020401116433781247), (1, 0.020044434817535654), (2, 0.0181593555308088), (3, 0.023979757098199432), (4, 0.023007203491147963), (5, 0.058069388566351285), (6, 0.0178695866558513), (7, 0.008679201150604894), (8, 0.05197472558716146), (9, 0.018691474239652044), (10, 0.02602629687366162), (11, 0.031140627675134896), (12, 0.02852703773003549), (13, 0.02042078847060626), (14, 0.018247651090785792), (15, 0.02579220666338637), (16, 0.05326877837731897), (17, 0.0270592503719723), (18, 0.030488837306061), (19, 0.024873332544166613), (20, 0.04650290125971606), (21, 0.031245039926335226), (22, 0.011919466851126444), (23, 0.08341325306311001), (24, 0.026003064967774325), (25, 0.03549424624962887), (26, 0.07442536600759528), (27, 0.05689709793041163), (28, 0.02294930058535654), (29, 0.07022821937602798), (30, 0.019977338290593394), (31, 0.034503323949346104), (32, 0.03335578591765926), (33, 0.024192961046354235), (34, 0.02380869893626156), (35, 0.08707223416576379), (36, 0.020681777121886

4364

# Get all Movies Sorted

In [58]:
Sorted_Similer_Movies = sorted(Recommendation_Score, key=lambda x:x[1],reverse = True)
print(Sorted_Similer_Movies)

[(614, 1.0), (895, 0.2468483005961075), (702, 0.22740697185280498), (108, 0.21773503457162352), (376, 0.21551706307562637), (191, 0.20314860664206105), (2320, 0.2002217519116221), (70, 0.19277042169523773), (565, 0.19018642962303295), (308, 0.185209699811056), (2577, 0.18500934084564447), (210, 0.18245434191448826), (3459, 0.1783338020499201), (4037, 0.17753344479154012), (324, 0.17378554553313966), (135, 0.1713987049471285), (2323, 0.1602576250508967), (2099, 0.15638171257474737), (3313, 0.15571831888621496), (862, 0.14597102597205902), (2256, 0.14557046664709744), (3359, 0.14487682628677773), (2673, 0.1414553243303022), (222, 0.1329628971641047), (3188, 0.13221632755513726), (2952, 0.1275582685506111), (703, 0.12499893505007051), (1099, 0.12462175871850417), (3655, 0.12389943436396036), (550, 0.12248359263014635), (585, 0.11354942395812136), (1004, 0.10932711774587599), (3885, 0.10879577646354265), (1075, 0.10789109815009196), (2963, 0.10744825811520133), (4175, 0.1058384275193819), 

In [ ]:
print('Top 5 movies according to your choice:\n')
i=1
for movie in Sorted_Similer_Movies:
    index=movie[0]
    title_from_index = df[df.index==index]['Movie_Title'].values[0]
    if(i<6):
        print(i,'')